import React from "react";
import { useNavigate } from "react-router-dom";

const Disclaimer = () => {
  const navigate = useNavigate();

  return (
    <div className="font-sans text-slate-900 overflow-x-hidden">

      {/* NAVBAR */}
      <nav className="fixed top-0 w-full z-50 bg-white/90 backdrop-blur-xl border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-8 py-3 flex justify-between items-center">

          <div className="flex items-center gap-1">
            <img src="/logo.png" className="w-16 p-0 " alt="logo" />
            <span className="text-xl font-extrabold tracking-tight text-slate-900">
              ApnaVakil
            </span>
          </div>

          <button
            onClick={() => navigate("/")}
            className="bg-gradient-to-r from-indigo-500 to-purple-500 text-white px-6 py-2 rounded-xl shadow-lg hover:scale-105 transition"
          >
            Back Home
          </button>
        </div>
      </nav>

      {/* HERO */}
      <section className="relative pt-32 pb-16 overflow-hidden bg-slate-50">
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-100 via-purple-100 to-pink-100" />
        <div className="absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_top,_white,_transparent_70%)]" />

        <div className="relative max-w-4xl mx-auto px-6 text-center">

          <h1 className="text-5xl md:text-6xl font-extrabold mb-6">
            Disclaimer
          </h1>

          <p className="text-lg text-slate-600">
            Important information regarding the use of Apna Vakil services.
          </p>
        </div>
      </section>

      {/* DISCLAIMER CONTENT */}
      <section className="relative py-24 bg-white">
        <div className="max-w-4xl mx-auto px-6">

          <div className="bg-white rounded-3xl shadow-2xl p-10 md:p-14 border border-slate-200">

            <h2 className="text-3xl font-bold mb-8 text-slate-900">
              Legal Disclaimer
            </h2>

            <div className="space-y-6 text-slate-700 leading-relaxed text-lg">

              <p>
                ⚠️ The information provided on the <strong>Apna Vakil</strong> website and through its
                services, including any content generated using automated or
                AI-powered tools, is intended solely for general informational
                purposes.
              </p>

              <p>
                Apna Vakil <strong>does not provide legal advice</strong>. The
                content generated by the platform should not be considered a
                substitute for professional legal consultation.
              </p>

              <p>
                While we strive to ensure the accuracy and reliability of the
                information provided, laws and regulations may change and may
                vary depending on jurisdiction and specific circumstances.
              </p>

              <p>
                Users are strongly advised to consult a{" "}
                <strong>qualified and licensed legal practitioner</strong>{" "}
                before taking any legal action or making decisions based on
                the information provided by the platform.
              </p>

              <p>
                By using the Apna Vakil platform, you acknowledge and agree
                that the platform is intended for informational assistance
                only and that you are responsible for verifying any legal
                information obtained through the service.
              </p>

              <p>
                Apna Vakil shall not be held liable for any actions taken or
                decisions made based on the information generated by the
                platform.
              </p>

            </div>

          </div>

        </div>
      </section>

      {/* FOOTER */}
      <footer className="bg-slate-900 text-white py-10">
        <div className="max-w-7xl mx-auto px-8 text-center text-slate-400">
          <p>
            © {new Date().getFullYear()} Apna Vakil. All Rights Reserved.
            Not a substitute for licensed legal counsel.
          </p>
        </div>
      </footer>

    </div>
  );
};

export default Disclaimer;